### ISSUE TITLE
Inaccurate panic reason in certain cases

### ISSUE THREAD

**Issue by mzohreva** [fortanix/rust-sgx#235]
The following program produces an incorrect panic reason:

```rust
fn main() {
    std::panic::catch_unwind(|| {
        panic!("one");
    });

    panic!("two");
}
```
Expected output:
```
...
Enclave panicked: thread 'main' panicked at 'two', src/main.rs:6:5
...
```
Got:
```
...
Enclave panicked: thread 'main' panicked at 'one', src/main.rs:3:9
...
```

If a usercall is inserted before the second panic, then a correct panic message is generated, e.g.:

```rust
fn main() {
    std::panic::catch_unwind(|| {
        panic!("one");
    });
    std::time::Instant::now(); // any usercall would work
    panic!("two");
}
```
Output:
```
...
Enclave panicked: thread 'main' panicked at 'two', src/main.rs:6:5
...
```

**Comment by mzohreva** [comment]
This issue is related to failure of [`ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs) test in SGX

**Comment by jethrogb** [comment]
Yeah this is because of the way the panic buffer passing in r10 works. Jeffrey and I came up with a plan to change the exit usercall to be more sane. I'll see if I can remember the details.

**Comment by jethrogb** [comment]
Plan is to adjust the `exit` call as follows:

```rust
pub fn exit(panic: bool, message: *const u8, len: usize) -> !
```

If `panic` is `true`, `message` may be non-NULL. In that case `message` points to a userspace buffer of length `len` containing the panic message.

The enclave should call `alloc` to allocate (and grow) the buffer as needed at panic time. The enclave could pre-allocate a small single global buffer that it can use once in case of allocation failure at panic time.

Even with all this, we still need to make sure that the panic message for panics that are caught but not resumed don't make it outside enclave memory (information leakage).
